version: '3.3'
services:
  orb-slam-service:
    image: ros:noetic
    container_name: orb_slam
    privileged: true
    restart: "no"
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
      - "DISPLAY"
      - QT_X11_NO_MITSHM=1
    volumes:
      - /home/${USER}:/home/cvrsg
      - /media/cvrsg:/media/cvrsg
    # deploy:
    #   resources:
    #      limits:
    #         cpus: '2'
    #         memory: 4G
    #      reservations:
    #         cpus: '0.5'
    #         memory: 200M
    command: ["sh"]
    # user: wz
